### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dgslos** [KatyBrown/CIAlign#48]
Maybe CIAlign could throw a more informative error if sequence lengths are not the same instead of the error below?

```
CIAlign/utilityFunctions.py:98: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array(seqs[1:])
Traceback (most recent call last):
  File "/home/dslos/.virtualenvs/cialign/bin/CIAlign", line 41, in <module>
    main()
  File "/home/dslos/.virtualenvs/cialign/bin/CIAlign", line 16, in main
    parser = argP.getParser()
  File "/home/dslos/.virtualenvs/cialign/lib/python3.10/site-packages/CIAlign/argP.py", line 150, in getParser
    n_col = np.shape(arr)[1]
IndexError: tuple index out of range
```

**Comment by KatyBrown** [comment]
Hi,
You're right - thanks very much - this has been an ongoing issue we've been meaning to address. I will ensure this is changed in the next minor release.
Katy

**Comment by dgslos** [comment]
Shouldn't be to complex. You could do:

```
def FastaToArray(infile, log=None, outfile_stem=None):
    '''
    Convert an alignment into a numpy array.
    Parameters
    ----------
    infile: string
        path to input alignment file in FASTA format
    log: logging.Logger
        An open log file object
    Returns
    -------
    arr: np.array
        2D numpy array in the same order as fasta_dict where each row
        represents a single column in the alignment and each column a
        single sequence.
    nams: list
        List of sequence names in the same order as in the input file
    '''

    formatErrorMessage = "The MSA file needs to be in FASTA format."
    nams = []
    seqs = []
    nam = ""
    string_seq = []
    seq=""
    n_seq_seen = 0
    with open("fungi_tef1_reference.fasta") as input:
        for line in input:
            line = line.strip()
            if len(line) == 0:
                continue
            if line[0] == ">":
                if n_seq_seen == 1:
                    seq_length = len(''.join(seq))
                elif n_seq_seen > 1:
                    if seq_length != len(seq):
                        raise ValueError("Sequences must all be the same length")
                seqs.append([s.upper() for s in seq])
                nams.append(nam)
                seq = []
                nam = line.replace(">", "")
                n_seq_seen += 1

            else:
                if len(nams) == 0:
                    if log:
                        log.error(formatErrorMessage)
                    print(formatErrorMessage)
                    exit(1)
                seq += list(line)
    seqs.append(np.array([s.upper() for s in seq]))
    nams.append(nam)
    arr = np.array(seqs[1:])
    return (arr, nams[1:])
```
