### ISSUE TITLE
Missing modules with installation

### ISSUE THREAD

**Issue by dgslos** [KatyBrown/CIAlign#52]
I'm on Ubuntu 22.04 with python 3.10.6 and the installation with pip from PyPi or cloning from the git repo is no longer working properly. Several dependencies are missing.

I fixed it by installing them seperatly. Is it possible to add all the dependencies in the setup.py?

Part of the errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/CIAlign", line 8, in <module>
    import CIAlign.runCIAlign as runCIAlign
  File "/usr/local/venvs/cialign/lib/python3.10/site-packages/CIAlign/runCIAlign.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/CIAlign", line 10, in <module>
    import argP
ModuleNotFoundError: No module named 'argP'
```

**Comment by KatyBrown** [comment]
Sorry for the very slow response, but this has now been fixed.
