### ISSUE TITLE
Backtrace output instead of clean error messages?

### ISSUE THREAD

**Issue by tseemann** [KatyBrown/CIAlign#6]
```
 $ CIAlign 
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/CIAlign", line 599, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/bin/CIAlign", line 245, in main
    raise RuntimeError("Input alignment must be provided")
RuntimeError: Input alignment must be provided
```

**Comment by schnamo** [comment]
- thank you for raising this issue, it's been resolved
- backtrace output replaced by clean error message
